In [18]:
import numpy as np

# Run xml on Python

In [19]:
state_space = [10,20,30,40,50,60,70,80,90,100] # density (#car/mile)
act_space = [-10,10]

den_cri = 60
#den_jam = 120

In [20]:
#Initialize Q-table with all zeros
Q    = np.zeros([len(state_space),len(act_space)])
Qnew = np.ones([len(state_space),len(act_space)])

# Set learning parameters
learning = 0.8
discount = 0.95
num_episodes = 2000
max_gap = 0.01 

In [21]:
def step(s,a):
    global sp
    den = state_space[s] + act_space[a]
    for i in range(len(state_space)):
        
        if i == 0:
            if 0 <= den < state_space[i]:
                sp = i
        elif state_space[i-1] <= den < state_space[i]:
            sp = i
            
    # make it to be continuous??
    
    if den_cri - den >= 0:
        #r = 1/(den_cri - den +1)
        #r = 1/(den - den_cri+1)**2 
        r = 1/(den_cri - den +1)
    elif den_cri - den <= 0:
        #r = 1/(den - den_cri +1)
        #r = 1/(den - den_cri+1)**2 
        r = den_cri - den
    return sp, r

In [22]:
r_list = []
for i in range(num_episodes):
    
    # Reset the environment
    s     = 0
    r_sum = 0
    j     = 0
    
    while j < 5000:
            
        # Q-table iteration
            
        j += 1
        noise = np.random.randn(1,len(act_space))*(1./(i+1))
        a = np.argmax(Q[s,:] + noise)
        s1,r = step(s,a)
        
        Q[s,a] = Q[s,a] + learning * (r + discount * np.max( Q[s1,:] ) - Q[s,a] )
        
        r_sum += r
        s = s1
        
        gap = abs(Qnew[s,a] - Q[s,a])
        
        if gap < max_gap:
            break
        
        Qnew[s,a] = Q[s,a]
        
    r_list.append(r_sum)

In [23]:
print(Q) # continuous, not differentiable (symmetric)

[[ 5.55366364e-02  1.79171583e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.23670151e-02  1.88344927e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.97768135e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.97663346e+01 -1.60000000e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [-3.99767560e+02 -4.13292272e+02]
 [ 0.00000000e+00  0.00000000e+00]]


In [24]:
print(Q) # continuous, differentiable  (symmetric)

[[ 5.55366364e-02  1.79171583e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.23670151e-02  1.88344927e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.97768135e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.97663346e+01 -1.60000000e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [-3.99767560e+02 -4.13292272e+02]
 [ 0.00000000e+00  0.00000000e+00]]


In [25]:
print(Q) #  not-continous (asymmetric)
print(np.argmax(Q[:,1]))

[[ 5.55366364e-02  1.79171583e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 5.23670151e-02  1.88344927e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.97768135e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [ 1.97663346e+01 -1.60000000e+01]
 [ 0.00000000e+00  0.00000000e+00]
 [-3.99767560e+02 -4.13292272e+02]
 [ 0.00000000e+00  0.00000000e+00]]
4


In [26]:
print(r_list)

[-4398.887207021953, 110.09639953542393, 1.0884027341444376, 1.0720092915214867, 1.0720092915214867, 1.0720092915214867, 1.0720092915214867, 1.0720092915214867, 0.07200929152148663, 0.07200929152148663, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024390243902439025, 0.024